kind: Deployment
apiVersion: apps/v1
metadata:
  name: akaes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: akaes
      id: "akaes"
  template:
    metadata:
      labels:
        app: akaes
        id: "akaes"
    spec:
      containers:
        - name: akaes
          image: alekseinovikov/akaes:arm64
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
              name: web
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: akaes-service
  name: "akaes-service"
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: akaes
  type: NodePort

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: akaes-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: akaes-service
                port:
                  number: 8080
