kind: Deployment
apiVersion: apps/v1
metadata:
  name: akaes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: akaes
      id: "akaes"
  template:
    metadata:
      labels:
        app: akaes
        id: "akaes"
    spec:
      containers:
        - name: akaes
          image: alekseinovikov/akaes:test2
          imagePullPolicy: Always
          env:
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq-service"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
          ports:
            - containerPort: 8080
              protocol: TCP
              name: web
            - containerPort: 8558
              name: management
            - containerPort: 2552
              name: remoting
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: akaes-service
  name: "akaes-service"
spec:
  ports:
    - name: web
      port: 8080
      protocol: TCP
    - name: management
      port: 8558
      targetPort: 8558
      protocol: TCP
    - name: remoting
      port: 2552
      targetPort: 2552
      protocol: TCP
  selector:
    app: akaes
  type: NodePort
