kind: Deployment
apiVersion: apps/v1
metadata:
  name: akaes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: akaes
      id: "akaes"
  template:
    metadata:
      labels:
        app: akaes
        id: "akaes"
    spec:
      containers:
        - name: akaes
          image: alekseinovikov/akaes:test1
          imagePullPolicy: Always
          env:
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
          ports:
            - containerPort: 8080
              protocol: TCP
              name: web
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: akaes-service
  name: "akaes-service"
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: akaes
  type: NodePort

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: akaes-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: akaes-service
              servicePort: 8080
          - path: /rabbitmq
            backend:
              serviceName: rabbitmq-service
              servicePort: 15672