apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: akaes-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: akaes-service
              servicePort: 8080
          - path: /rabbitmq/(.*)
            backend:
              serviceName: rabbitmq-service
              servicePort: 15672
